# GitHub Pages configuration for PATH-FINDER
# This ensures proper HTML processing

title: "PATH-FINDER: Ikigai Career Guidance Platform"
description: "Discover your life's purpose through the ancient Japanese philosophy of Ikigai"
url: "https://smdhussain06.github.io"
baseurl: "/PATH-FINDER"

# Build settings
plugins:
  - jekyll-relative-links

# Exclude files from processing
exclude:
  - app.py
  - requirements.txt
  - sampleusers.csv
  - __pycache__/
  - .git/
  - .gitignore

# Relative links settings
relative_links:
  enabled: true
  collections: true

# GitHub Pages settings
github:
  repository_name: PATH-FINDER
  repository_url: https://github.com/smdhussain06/PATH-FINDER